POST http://127.0.0.1:8000/webhooks/sync-clients/
Authorization: Bearer d6f351b2c2d6b6d726781056ffdef67f9ca4d9ea798c894423ec1646b4e73340
Content-Type: application/json

{
  "clientid": 1,
  "clientname": "Test Client",
  "aqueductclientnumber": "AQU12345",
  "dba": "Test DBA",
  "streetaddress": "123 Test St",
  "city": "Testville",
  "state": "CA",
  "zip": "90210",
  "country": "USA",
  "createdat": "2024-12-20T15:00:00Z"
}