name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main  # Run only for PRs to the main branch
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Standardize versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Ensure this matches your project's environment

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for the scan
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SonarCloud authentication
